module.exports = {
  apps: [
    {
      name: "nxs-backend",
      script: "./server/server.js",
      cwd: "./",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        CORS_ORIGIN: "http://localhost:3000",
        SMTP_HOST: "smtp.gmail.com",
        SMTP_PORT: 465,
        SMTP_SECURE: true,
        SMTP_USER: "it@vanguard-group.org",
        SMTP_PASS: "alebxmozexpbfzek",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/backend-error.log",
      out_file: "./logs/backend-out.log",
      log_file: "./logs/backend-combined.log",
      time: true,
    },
    {
      name: "nxs-frontend",
      script: "npx",
      args: "serve -s dist -l 3000",
      cwd: "./",
      env: {
        NODE_ENV: "production",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      error_file: "./logs/frontend-error.log",
      out_file: "./logs/frontend-out.log",
      log_file: "./logs/frontend-combined.log",
      time: true,
    },
  ],
};
